In [22]:
import numpy as np
import pandas as pd

In [ ]:
f = pd.DataFrame(np.random.randn(5,4),index = 'A B C D E'.split(),columns='W X Y Z'.split())

          W         X         Y         Z       new
A  0.985643  0.245570  1.548802  0.829917  2.534444
B -1.230272  1.373630 -1.236440  0.744622 -2.466712
C -1.792676  2.882264 -1.199685  1.436215 -2.992362
D  0.004926 -0.567590  0.960353 -1.073265  0.965279
E  1.054437  0.551652 -0.464550 -0.430863  0.589887

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,1-Jun-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,1-Jun-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,23-May-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')