In [22]:
import numpy as np
import pandas as pd

In [ ]:
f = pd.DataFrame(np.random.randn(5,4),index = 'A B C D E'.split(),columns='W X Y Z'.split())

          W         X         Y         Z       new
A  0.985643  0.245570  1.548802  0.829917  2.534444
B -1.230272  1.373630 -1.236440  0.744622 -2.466712
C -1.792676  2.882264 -1.199685  1.436215 -2.992362
D  0.004926 -0.567590  0.960353 -1.073265  0.965279
E  1.054437  0.551652 -0.464550 -0.430863  0.589887

In [60]:
f = pd.read_csv("banklist.csv")
f.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,1-Jun-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,1-Jun-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,23-May-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17

In [30]:
f.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

In [34]:
f['ST'].nunique()

44

In [38]:
f['ST'].unique()

array(['IL', 'WI', 'LA', 'UT', 'NJ', 'AR', 'GA', 'PA', 'TN', 'WA', 'CO',
       'PR', 'FL', 'MN', 'CA', 'MD', 'OK', 'OH', 'SC', 'VA', 'ID', 'TX',
       'CT', 'AZ', 'NV', 'NC', 'KY', 'MO', 'KS', 'AL', 'MI', 'IN', 'IA',
       'NE', 'MS', 'NM', 'OR', 'NY', 'MA', 'SD', 'WY', 'WV', 'NH', 'HI'],
      dtype=object)

In [46]:
f.groupby('ST').count().sort_values(by = 'Closing Date', ascending = False )['Closing Date'].head()

ST
GA    93
FL    75
IL    67
CA    41
MN    23
Name: Closing Date, dtype: int64

In [47]:
f.groupby("Acquiring Institution").count().sort_values(by = "Bank Name", ascending = False)['Closing Date'].head()

Acquiring Institution
No Acquirer                            31
State Bank and Trust Company           12
First-Citizens Bank & Trust Company    11
Ameris Bank                            10
U.S. Bank N.A.                          9
Name: Closing Date, dtype: int64

In [57]:
f[f["Acquiring Institution"] == "State Bank of Texas"]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
21,The National Republic Bank of Chicago,Chicago,IL,916,State Bank of Texas,24-Oct-14,6-Jan-16
450,Millennium State Bank of Texas,Dallas,TX,57667,State Bank of Texas,2-Jul-09,26-Oct-12

In [71]:
f[f['ST'] == 'CA'].groupby('City').count().sort_values(by = 'ST', ascending = False).head(1)

,Bank Name,ST,CERT,Acquiring Institution,Closing Date,Updated Date
City,,,,,,
Los Angeles,4,4,4,4,4,4

In [70]:
f[f['City'] == 'Los Angeles']

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
347,First Regional Bank,Los Angeles,CA,23011,First-Citizens Bank & Trust Company,29-Jan-10,4-Mar-16
391,California National Bank,Los Angeles,CA,34659,U.S. Bank N.A.,30-Oct-09,5-Sep-12
456,Mirae Bank,Los Angeles,CA,57332,Wilshire State Bank,26-Jun-09,20-Aug-12
507,Security Pacific Bank,Los Angeles,CA,23595,Pacific Western Bank,7-Nov-08,28-Aug-12

In [86]:
sum(f['Bank Name'].apply(lambda name : 'Bank' not in name ))

14

In [87]:
sum(f['Bank Name'].apply(lambda name : name.lower()[0] == 's'))

53

In [105]:
sum(f['CERT'] > 20000),len(f[f['CERT']>20000])

(417, 417)

In [107]:
sum(f['Bank Name'].apply(lambda name : len(name.split()) == 2))

114

In [110]:
sum(f['Closing Date'].apply(lambda date : date.split('-')[2] == '08'))

25